[project]
name = "billsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.10.5",
    "beautifulsoup4>=4.12.3",
    "bs4>=0.0.2",
    "fastapi[all]>=0.115.0",
    "sqlalchemy>=2.0.35",
]
